/*
 *
 * MasterPage constants
 *
 */

export const GET_CUSTOMERS = 'app/MasterPage/GET_CUSTOMERS';
export const GET_CUSTOMERS_SUCCESS = 'app/MasterPage/GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_ERROR = 'app/MasterPage/GET_CUSTOMERS_ERROR';

export const CREATE_CUSTOMER = 'app/MasterPage/CREATE_CUSTOMER';
export const CREATE_CUSTOMER_SUCCESS = 'app/MasterPage/CREATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_ERROR = 'app/MasterPage/CREATE_CUSTOMER_ERROR';

export const GET_PRODUCTION_MACHINES = 'app/MasterPage/GET_PRODUCTION_MACHINES';
export const GET_PRODUCTION_MACHINES_SUCCESS =
  'app/MasterPage/GET_PRODUCTION_MACHINES_SUCCESS';
export const GET_PRODUCTION_MACHINES_ERROR =
  'app/MasterPage/GET_PRODUCTION_MACHINES_ERROR';

export const CREATE_PRODUCTION_MACHINE =
  'app/MasterPage/CREATE_PRODUCTION_MACHINE';
export const CREATE_PRODUCTION_MACHINE_SUCCESS =
  'app/MasterPage/CREATE_PRODUCTION_MACHINE_SUCCESS';
export const CREATE_PRODUCTION_MACHINE_ERROR =
  'app/MasterPage/CREATE_PRODUCTION_MACHINE_ERROR';

export const GET_PRODUCTION_TASKS = 'app/MasterPage/GET_PRODUCTION_TASKS';
export const GET_PRODUCTION_TASKS_SUCCESS =
  'app/MasterPage/GET_PRODUCTION_TASKS_SUCCESS';
export const GET_PRODUCTION_TASKS_ERROR =
  'app/MasterPage/GET_PRODUCTION_TASKS_ERROR';

export const CREATE_PRODUCTION_TASK = 'app/MasterPage/CREATE_PRODUCTION_TASK';
export const CREATE_PRODUCTION_TASK_SUCCESS =
  'app/MasterPage/CREATE_PRODUCTION_TASK_SUCCESS';
export const CREATE_PRODUCTION_TASK_ERROR =
  'app/MasterPage/CREATE_PRODUCTION_TASK_ERROR';
